/*
 * E2B API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.e2b.api.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Status of the node
 */
@JsonAdapter(NodeStatus.Adapter.class)
public enum NodeStatus {
  
  NodeStatusReady("ready"),
  
  NodeStatusDraining("draining"),
  
  NodeStatusConnecting("connecting"),
  
  NodeStatusUnhealthy("unhealthy");

  private String value;

  NodeStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static NodeStatus fromValue(String value) {
    for (NodeStatus b : NodeStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<NodeStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final NodeStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public NodeStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return NodeStatus.fromValue(value);
    }
  }
}

