/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TemplateRef references a SandboxTemplate, which will be used to create the sandbox.
 */
@ApiModel(description = "TemplateRef references a SandboxTemplate, which will be used to create the sandbox.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-02-05T05:47:28.584Z[Etc/UTC]")
public class V1alpha1SandboxSetSpecTemplateRef {
    public static final String SERIALIZED_NAME_API_VERSION = "apiVersion";
    @SerializedName(SERIALIZED_NAME_API_VERSION)
    private String apiVersion;

    public static final String SERIALIZED_NAME_KIND = "kind";
    @SerializedName(SERIALIZED_NAME_KIND)
    private String kind;

    public static final String SERIALIZED_NAME_NAME = "name";
    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;

    public V1alpha1SandboxSetSpecTemplateRef apiVersion(String apiVersion) {

        this.apiVersion = apiVersion;
        return this;
    }

    /**
     * name of the SandboxTemplate apiVersion Default to v1
     *
     * @return apiVersion
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "name of the SandboxTemplate apiVersion Default to v1")

    public String getApiVersion() {
        return apiVersion;
    }

    public void setApiVersion(String apiVersion) {
        this.apiVersion = apiVersion;
    }

    public V1alpha1SandboxSetSpecTemplateRef kind(String kind) {

        this.kind = kind;
        return this;
    }

    /**
     * name of the SandboxTemplate kind Default to PodTemplate
     *
     * @return kind
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "name of the SandboxTemplate kind Default to PodTemplate")

    public String getKind() {
        return kind;
    }

    public void setKind(String kind) {
        this.kind = kind;
    }

    public V1alpha1SandboxSetSpecTemplateRef name(String name) {

        this.name = name;
        return this;
    }

    /**
     * name of the SandboxTemplate
     *
     * @return name
     **/
    @ApiModelProperty(required = true, value = "name of the SandboxTemplate")

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SandboxSetSpecTemplateRef v1alpha1SandboxSetSpecTemplateRef = (V1alpha1SandboxSetSpecTemplateRef)o;
        return Objects.equals(this.apiVersion, v1alpha1SandboxSetSpecTemplateRef.apiVersion) &&
            Objects.equals(this.kind, v1alpha1SandboxSetSpecTemplateRef.kind) &&
            Objects.equals(this.name, v1alpha1SandboxSetSpecTemplateRef.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(apiVersion, kind, name);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SandboxSetSpecTemplateRef {\n");
        sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
        sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

