/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * status defines the observed state of SandboxClaim
 */
@ApiModel(description = "status defines the observed state of SandboxClaim")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-02-05T05:47:28.584Z[Etc/UTC]")
public class V1alpha1SandboxClaimStatus {
    public static final String SERIALIZED_NAME_CLAIM_START_TIME = "claimStartTime";
    @SerializedName(SERIALIZED_NAME_CLAIM_START_TIME)
    private OffsetDateTime claimStartTime;

    public static final String SERIALIZED_NAME_CLAIMED_REPLICAS = "claimedReplicas";
    @SerializedName(SERIALIZED_NAME_CLAIMED_REPLICAS)
    private Integer claimedReplicas;

    public static final String SERIALIZED_NAME_COMPLETION_TIME = "completionTime";
    @SerializedName(SERIALIZED_NAME_COMPLETION_TIME)
    private OffsetDateTime completionTime;

    public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
    @SerializedName(SERIALIZED_NAME_CONDITIONS)
    private List<V1alpha1Conditions> conditions = null;

    public static final String SERIALIZED_NAME_MESSAGE = "message";
    @SerializedName(SERIALIZED_NAME_MESSAGE)
    private String message;

    public static final String SERIALIZED_NAME_OBSERVED_GENERATION = "observedGeneration";
    @SerializedName(SERIALIZED_NAME_OBSERVED_GENERATION)
    private Long observedGeneration;

    public static final String SERIALIZED_NAME_PHASE = "phase";
    @SerializedName(SERIALIZED_NAME_PHASE)
    private String phase;

    public V1alpha1SandboxClaimStatus claimStartTime(OffsetDateTime claimStartTime) {

        this.claimStartTime = claimStartTime;
        return this;
    }

    /**
     * ClaimStartTime is the timestamp when claiming started Used for calculating timeout
     *
     * @return claimStartTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "ClaimStartTime is the timestamp when claiming started Used for calculating timeout")

    public OffsetDateTime getClaimStartTime() {
        return claimStartTime;
    }

    public void setClaimStartTime(OffsetDateTime claimStartTime) {
        this.claimStartTime = claimStartTime;
    }

    public V1alpha1SandboxClaimStatus claimedReplicas(Integer claimedReplicas) {

        this.claimedReplicas = claimedReplicas;
        return this;
    }

    /**
     * ClaimedReplicas indicates how many sandboxes are currently claimed (total) This is determined by querying
     * sandboxes with matching ownerReference Only updated during Pending and Claiming phases
     *
     * @return claimedReplicas
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "ClaimedReplicas indicates how many sandboxes are currently claimed (total) This is determined by "
            + "querying sandboxes with matching ownerReference Only updated during Pending and Claiming phases")

    public Integer getClaimedReplicas() {
        return claimedReplicas;
    }

    public void setClaimedReplicas(Integer claimedReplicas) {
        this.claimedReplicas = claimedReplicas;
    }

    public V1alpha1SandboxClaimStatus completionTime(OffsetDateTime completionTime) {

        this.completionTime = completionTime;
        return this;
    }

    /**
     * CompletionTime is the timestamp when the claim reached Completed phase Used for TTL calculation
     *
     * @return completionTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "CompletionTime is the timestamp when the claim reached Completed phase Used for TTL calculation")

    public OffsetDateTime getCompletionTime() {
        return completionTime;
    }

    public void setCompletionTime(OffsetDateTime completionTime) {
        this.completionTime = completionTime;
    }

    public V1alpha1SandboxClaimStatus conditions(List<V1alpha1Conditions> conditions) {

        this.conditions = conditions;
        return this;
    }

    public V1alpha1SandboxClaimStatus addConditionsItem(V1alpha1Conditions conditionsItem) {
        if (this.conditions == null) {
            this.conditions = new ArrayList<>();
        }
        this.conditions.add(conditionsItem);
        return this;
    }

    /**
     * Conditions represent the current state of the SandboxClaim
     *
     * @return conditions
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Conditions represent the current state of the SandboxClaim")

    public List<V1alpha1Conditions> getConditions() {
        return conditions;
    }

    public void setConditions(List<V1alpha1Conditions> conditions) {
        this.conditions = conditions;
    }

    public V1alpha1SandboxClaimStatus message(String message) {

        this.message = message;
        return this;
    }

    /**
     * Message provides human-readable details about the current phase
     *
     * @return message
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Message provides human-readable details about the current phase")

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public V1alpha1SandboxClaimStatus observedGeneration(Long observedGeneration) {

        this.observedGeneration = observedGeneration;
        return this;
    }

    /**
     * ObservedGeneration is the most recent generation observed
     *
     * @return observedGeneration
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "ObservedGeneration is the most recent generation observed")

    public Long getObservedGeneration() {
        return observedGeneration;
    }

    public void setObservedGeneration(Long observedGeneration) {
        this.observedGeneration = observedGeneration;
    }

    public V1alpha1SandboxClaimStatus phase(String phase) {

        this.phase = phase;
        return this;
    }

    /**
     * Phase represents the current phase of the claim Claiming: In the process of claiming sandboxes Completed: Claim
     * process finished (either all replicas claimed or timeout reached)
     *
     * @return phase
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "Phase represents the current phase of the claim Claiming: In the process of claiming sandboxes "
            + "Completed: Claim process finished (either all replicas claimed or timeout reached)")

    public String getPhase() {
        return phase;
    }

    public void setPhase(String phase) {
        this.phase = phase;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SandboxClaimStatus v1alpha1SandboxClaimStatus = (V1alpha1SandboxClaimStatus)o;
        return Objects.equals(this.claimStartTime, v1alpha1SandboxClaimStatus.claimStartTime) &&
            Objects.equals(this.claimedReplicas, v1alpha1SandboxClaimStatus.claimedReplicas) &&
            Objects.equals(this.completionTime, v1alpha1SandboxClaimStatus.completionTime) &&
            Objects.equals(this.conditions, v1alpha1SandboxClaimStatus.conditions) &&
            Objects.equals(this.message, v1alpha1SandboxClaimStatus.message) &&
            Objects.equals(this.observedGeneration, v1alpha1SandboxClaimStatus.observedGeneration) &&
            Objects.equals(this.phase, v1alpha1SandboxClaimStatus.phase);
    }

    @Override
    public int hashCode() {
        return Objects.hash(claimStartTime, claimedReplicas, completionTime, conditions, message, observedGeneration,
            phase);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SandboxClaimStatus {\n");
        sb.append("    claimStartTime: ").append(toIndentedString(claimStartTime)).append("\n");
        sb.append("    claimedReplicas: ").append(toIndentedString(claimedReplicas)).append("\n");
        sb.append("    completionTime: ").append(toIndentedString(completionTime)).append("\n");
        sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    observedGeneration: ").append(toIndentedString(observedGeneration)).append("\n");
        sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

