/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * spec defines the desired characteristics of a volume requested by a pod author. More info:
 * https://kubernetes.io/docs/concepts/storage/persistent-volumes#persistentvolumeclaims
 */
@ApiModel(
    description = "spec defines the desired characteristics of a volume requested by a pod author. More info: "
        + "https://kubernetes.io/docs/concepts/storage/persistent-volumes#persistentvolumeclaims")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-01-23T10:04:45.718Z[Etc/UTC]")
public class V1alpha1SandboxSetSpecSpec {
    public static final String SERIALIZED_NAME_ACCESS_MODES = "accessModes";
    @SerializedName(SERIALIZED_NAME_ACCESS_MODES)
    private List<String> accessModes = null;

    public static final String SERIALIZED_NAME_DATA_SOURCE = "dataSource";
    @SerializedName(SERIALIZED_NAME_DATA_SOURCE)
    private V1alpha1SandboxSetSpecSpecDataSource dataSource;

    public static final String SERIALIZED_NAME_DATA_SOURCE_REF = "dataSourceRef";
    @SerializedName(SERIALIZED_NAME_DATA_SOURCE_REF)
    private V1alpha1SandboxSetSpecSpecDataSourceRef dataSourceRef;

    public static final String SERIALIZED_NAME_RESOURCES = "resources";
    @SerializedName(SERIALIZED_NAME_RESOURCES)
    private V1alpha1SandboxSetSpecSpecResources resources;

    public static final String SERIALIZED_NAME_SELECTOR = "selector";
    @SerializedName(SERIALIZED_NAME_SELECTOR)
    private V1alpha1SandboxSetSpecSpecSelector selector;

    public static final String SERIALIZED_NAME_STORAGE_CLASS_NAME = "storageClassName";
    @SerializedName(SERIALIZED_NAME_STORAGE_CLASS_NAME)
    private String storageClassName;

    public static final String SERIALIZED_NAME_VOLUME_ATTRIBUTES_CLASS_NAME = "volumeAttributesClassName";
    @SerializedName(SERIALIZED_NAME_VOLUME_ATTRIBUTES_CLASS_NAME)
    private String volumeAttributesClassName;

    public static final String SERIALIZED_NAME_VOLUME_MODE = "volumeMode";
    @SerializedName(SERIALIZED_NAME_VOLUME_MODE)
    private String volumeMode;

    public static final String SERIALIZED_NAME_VOLUME_NAME = "volumeName";
    @SerializedName(SERIALIZED_NAME_VOLUME_NAME)
    private String volumeName;

    public V1alpha1SandboxSetSpecSpec accessModes(List<String> accessModes) {

        this.accessModes = accessModes;
        return this;
    }

    public V1alpha1SandboxSetSpecSpec addAccessModesItem(String accessModesItem) {
        if (this.accessModes == null) {
            this.accessModes = new ArrayList<>();
        }
        this.accessModes.add(accessModesItem);
        return this;
    }

    /**
     * accessModes contains the desired access modes the volume should have. More info:
     * https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
     *
     * @return accessModes
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "accessModes contains the desired access modes the volume should have. More info: https://kubernetes"
            + ".io/docs/concepts/storage/persistent-volumes#access-modes-1")

    public List<String> getAccessModes() {
        return accessModes;
    }

    public void setAccessModes(List<String> accessModes) {
        this.accessModes = accessModes;
    }

    public V1alpha1SandboxSetSpecSpec dataSource(V1alpha1SandboxSetSpecSpecDataSource dataSource) {

        this.dataSource = dataSource;
        return this;
    }

    /**
     * Get dataSource
     *
     * @return dataSource
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SandboxSetSpecSpecDataSource getDataSource() {
        return dataSource;
    }

    public void setDataSource(V1alpha1SandboxSetSpecSpecDataSource dataSource) {
        this.dataSource = dataSource;
    }

    public V1alpha1SandboxSetSpecSpec dataSourceRef(V1alpha1SandboxSetSpecSpecDataSourceRef dataSourceRef) {

        this.dataSourceRef = dataSourceRef;
        return this;
    }

    /**
     * Get dataSourceRef
     *
     * @return dataSourceRef
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SandboxSetSpecSpecDataSourceRef getDataSourceRef() {
        return dataSourceRef;
    }

    public void setDataSourceRef(V1alpha1SandboxSetSpecSpecDataSourceRef dataSourceRef) {
        this.dataSourceRef = dataSourceRef;
    }

    public V1alpha1SandboxSetSpecSpec resources(V1alpha1SandboxSetSpecSpecResources resources) {

        this.resources = resources;
        return this;
    }

    /**
     * Get resources
     *
     * @return resources
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SandboxSetSpecSpecResources getResources() {
        return resources;
    }

    public void setResources(V1alpha1SandboxSetSpecSpecResources resources) {
        this.resources = resources;
    }

    public V1alpha1SandboxSetSpecSpec selector(V1alpha1SandboxSetSpecSpecSelector selector) {

        this.selector = selector;
        return this;
    }

    /**
     * Get selector
     *
     * @return selector
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SandboxSetSpecSpecSelector getSelector() {
        return selector;
    }

    public void setSelector(V1alpha1SandboxSetSpecSpecSelector selector) {
        this.selector = selector;
    }

    public V1alpha1SandboxSetSpecSpec storageClassName(String storageClassName) {

        this.storageClassName = storageClassName;
        return this;
    }

    /**
     * storageClassName is the name of the StorageClass required by the claim. More info:
     * https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1
     *
     * @return storageClassName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "storageClassName is the name of the StorageClass required by the claim. More info: "
            + "https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1")

    public String getStorageClassName() {
        return storageClassName;
    }

    public void setStorageClassName(String storageClassName) {
        this.storageClassName = storageClassName;
    }

    public V1alpha1SandboxSetSpecSpec volumeAttributesClassName(String volumeAttributesClassName) {

        this.volumeAttributesClassName = volumeAttributesClassName;
        return this;
    }

    /**
     * volumeAttributesClassName may be used to set the VolumeAttributesClass used by this claim. If specified, the CSI
     * driver will create or update the volume with the attributes defined in the corresponding VolumeAttributesClass.
     * This has a different purpose than storageClassName, it can be changed after the claim is created. An empty string
     * value means that no VolumeAttributesClass will be applied to the claim but it&#39;s not allowed to reset this
     * field to empty string once it is set. If unspecified and the PersistentVolumeClaim is unbound, the default
     * VolumeAttributesClass will be set by the persistentvolume controller if it exists. If the resource referred to by
     * volumeAttributesClass does not exist, this PersistentVolumeClaim will be set to a Pending state, as reflected by
     * the modifyVolumeStatus field, until such as a resource exists. More info:
     * https://kubernetes.io/docs/concepts/storage/volume-attributes-classes/ (Beta) Using this field requires the
     * VolumeAttributesClass feature gate to be enabled (off by default).
     *
     * @return volumeAttributesClassName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "volumeAttributesClassName may be used to set the VolumeAttributesClass used by this claim. If "
            + "specified, the CSI driver will create or update the volume with the attributes defined in the "
            + "corresponding VolumeAttributesClass. This has a different purpose than storageClassName, it can be "
            + "changed after the claim is created. An empty string value means that no VolumeAttributesClass will be "
            + "applied to the claim but it's not allowed to reset this field to empty string once it is set. If "
            + "unspecified and the PersistentVolumeClaim is unbound, the default VolumeAttributesClass will be set by"
            + " the persistentvolume controller if it exists. If the resource referred to by volumeAttributesClass "
            + "does not exist, this PersistentVolumeClaim will be set to a Pending state, as reflected by the "
            + "modifyVolumeStatus field, until such as a resource exists. More info: https://kubernetes"
            + ".io/docs/concepts/storage/volume-attributes-classes/ (Beta) Using this field requires the "
            + "VolumeAttributesClass feature gate to be enabled (off by default).")

    public String getVolumeAttributesClassName() {
        return volumeAttributesClassName;
    }

    public void setVolumeAttributesClassName(String volumeAttributesClassName) {
        this.volumeAttributesClassName = volumeAttributesClassName;
    }

    public V1alpha1SandboxSetSpecSpec volumeMode(String volumeMode) {

        this.volumeMode = volumeMode;
        return this;
    }

    /**
     * volumeMode defines what type of volume is required by the claim. Value of Filesystem is implied when not included
     * in claim spec.
     *
     * @return volumeMode
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "volumeMode defines what type of volume is required by the claim. Value of Filesystem is implied when"
            + " not included in claim spec.")

    public String getVolumeMode() {
        return volumeMode;
    }

    public void setVolumeMode(String volumeMode) {
        this.volumeMode = volumeMode;
    }

    public V1alpha1SandboxSetSpecSpec volumeName(String volumeName) {

        this.volumeName = volumeName;
        return this;
    }

    /**
     * volumeName is the binding reference to the PersistentVolume backing this claim.
     *
     * @return volumeName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "volumeName is the binding reference to the PersistentVolume backing this claim.")

    public String getVolumeName() {
        return volumeName;
    }

    public void setVolumeName(String volumeName) {
        this.volumeName = volumeName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SandboxSetSpecSpec v1alpha1SandboxSetSpecSpec = (V1alpha1SandboxSetSpecSpec)o;
        return Objects.equals(this.accessModes, v1alpha1SandboxSetSpecSpec.accessModes) &&
            Objects.equals(this.dataSource, v1alpha1SandboxSetSpecSpec.dataSource) &&
            Objects.equals(this.dataSourceRef, v1alpha1SandboxSetSpecSpec.dataSourceRef) &&
            Objects.equals(this.resources, v1alpha1SandboxSetSpecSpec.resources) &&
            Objects.equals(this.selector, v1alpha1SandboxSetSpecSpec.selector) &&
            Objects.equals(this.storageClassName, v1alpha1SandboxSetSpecSpec.storageClassName) &&
            Objects.equals(this.volumeAttributesClassName, v1alpha1SandboxSetSpecSpec.volumeAttributesClassName) &&
            Objects.equals(this.volumeMode, v1alpha1SandboxSetSpecSpec.volumeMode) &&
            Objects.equals(this.volumeName, v1alpha1SandboxSetSpecSpec.volumeName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(accessModes, dataSource, dataSourceRef, resources, selector, storageClassName,
            volumeAttributesClassName, volumeMode, volumeName);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SandboxSetSpecSpec {\n");
        sb.append("    accessModes: ").append(toIndentedString(accessModes)).append("\n");
        sb.append("    dataSource: ").append(toIndentedString(dataSource)).append("\n");
        sb.append("    dataSourceRef: ").append(toIndentedString(dataSourceRef)).append("\n");
        sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
        sb.append("    selector: ").append(toIndentedString(selector)).append("\n");
        sb.append("    storageClassName: ").append(toIndentedString(storageClassName)).append("\n");
        sb.append("    volumeAttributesClassName: ").append(toIndentedString(volumeAttributesClassName)).append("\n");
        sb.append("    volumeMode: ").append(toIndentedString(volumeMode)).append("\n");
        sb.append("    volumeName: ").append(toIndentedString(volumeName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

