/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.kubernetes.client.custom.Quantity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * status represents the current information/status of a persistent volume claim. Read-only. More info:
 * https://kubernetes.io/docs/concepts/storage/persistent-volumes#persistentvolumeclaims
 */
@ApiModel(
    description = "status represents the current information/status of a persistent volume claim. Read-only. More "
        + "info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#persistentvolumeclaims")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-01-23T10:04:45.718Z[Etc/UTC]")
public class V1alpha1SandboxSetSpecStatus {
    public static final String SERIALIZED_NAME_ACCESS_MODES = "accessModes";
    @SerializedName(SERIALIZED_NAME_ACCESS_MODES)
    private List<String> accessModes = null;
    public static final String SERIALIZED_NAME_ALLOCATED_RESOURCE_STATUSES = "allocatedResourceStatuses";
    @SerializedName(SERIALIZED_NAME_ALLOCATED_RESOURCE_STATUSES)
    private Map<String, String> allocatedResourceStatuses = null;

    public static final String SERIALIZED_NAME_ALLOCATED_RESOURCES = "allocatedResources";
    @SerializedName(SERIALIZED_NAME_ALLOCATED_RESOURCES)
    private Map<String, Quantity> allocatedResources = null;

    public static final String SERIALIZED_NAME_CAPACITY = "capacity";
    @SerializedName(SERIALIZED_NAME_CAPACITY)
    private Map<String, Quantity> capacity = null;

    public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
    @SerializedName(SERIALIZED_NAME_CONDITIONS)
    private List<V1alpha1SandboxSetSpecStatusConditions> conditions = null;

    public static final String SERIALIZED_NAME_CURRENT_VOLUME_ATTRIBUTES_CLASS_NAME
        = "currentVolumeAttributesClassName";
    @SerializedName(SERIALIZED_NAME_CURRENT_VOLUME_ATTRIBUTES_CLASS_NAME)
    private String currentVolumeAttributesClassName;

    public static final String SERIALIZED_NAME_MODIFY_VOLUME_STATUS = "modifyVolumeStatus";
    @SerializedName(SERIALIZED_NAME_MODIFY_VOLUME_STATUS)
    private V1alpha1SandboxSetSpecStatusModifyVolumeStatus modifyVolumeStatus;

    public static final String SERIALIZED_NAME_PHASE = "phase";
    @SerializedName(SERIALIZED_NAME_PHASE)
    private String phase;

    public V1alpha1SandboxSetSpecStatus accessModes(List<String> accessModes) {

        this.accessModes = accessModes;
        return this;
    }

    public V1alpha1SandboxSetSpecStatus addAccessModesItem(String accessModesItem) {
        if (this.accessModes == null) {
            this.accessModes = new ArrayList<>();
        }
        this.accessModes.add(accessModesItem);
        return this;
    }

    /**
     * accessModes contains the actual access modes the volume backing the PVC has. More info:
     * https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
     *
     * @return accessModes
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "accessModes contains the actual access modes the volume backing the PVC has. More info: "
            + "https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1")

    public List<String> getAccessModes() {
        return accessModes;
    }

    public void setAccessModes(List<String> accessModes) {
        this.accessModes = accessModes;
    }

    public V1alpha1SandboxSetSpecStatus allocatedResourceStatuses(Map<String, String> allocatedResourceStatuses) {

        this.allocatedResourceStatuses = allocatedResourceStatuses;
        return this;
    }

    public V1alpha1SandboxSetSpecStatus putAllocatedResourceStatusesItem(String key,
        String allocatedResourceStatusesItem) {
        if (this.allocatedResourceStatuses == null) {
            this.allocatedResourceStatuses = new HashMap<>();
        }
        this.allocatedResourceStatuses.put(key, allocatedResourceStatusesItem);
        return this;
    }

    /**
     * allocatedResourceStatuses stores status of resource being resized for the given PVC. Key names follow standard
     * Kubernetes label syntax. Valid values are either:  * Un-prefixed keys:   - storage - the capacity of the volume.
     * * Custom resources must use implementation-defined prefixed names such as
     * \&quot;example.com/my-custom-resource\&quot; Apart from above values - keys that are unprefixed or have
     * kubernetes.io prefix are considered reserved and hence may not be used.  ClaimResourceStatus can be in any of
     * following states:  - ControllerResizeInProgress:   State set when resize controller starts resizing the volume in
     * control-plane.  - ControllerResizeFailed:   State set when resize has failed in resize controller with a terminal
     * error.  - NodeResizePending:   State set when resize controller has finished resizing the volume but further
     * resizing of   volume is needed on the node.  - NodeResizeInProgress:   State set when kubelet starts resizing the
     * volume.  - NodeResizeFailed:   State set when resizing has failed in kubelet with a terminal error. Transient
     * errors don&#39;t set   NodeResizeFailed. For example: if expanding a PVC for more capacity - this field can be
     * one of the following states:  - pvc.status.allocatedResourceStatus[&#39;storage&#39;] &#x3D;
     * \&quot;ControllerResizeInProgress\&quot;      - pvc.status.allocatedResourceStatus[&#39;storage&#39;] &#x3D;
     * \&quot;ControllerResizeFailed\&quot;      - pvc.status.allocatedResourceStatus[&#39;storage&#39;] &#x3D;
     * \&quot;NodeResizePending\&quot;      - pvc.status.allocatedResourceStatus[&#39;storage&#39;] &#x3D;
     * \&quot;NodeResizeInProgress\&quot;      - pvc.status.allocatedResourceStatus[&#39;storage&#39;] &#x3D;
     * \&quot;NodeResizeFailed\&quot; When this field is not set, it means that no resize operation is in progress for
     * the given PVC.  A controller that receives PVC update with previously unknown resourceName or ClaimResourceStatus
     * should ignore the update for the purpose it was designed. For example - a controller that only is responsible for
     * resizing capacity of the volume, should ignore PVC updates that change other valid resources associated with PVC.
     * This is an alpha field and requires enabling RecoverVolumeExpansionFailure feature.
     *
     * @return allocatedResourceStatuses
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "allocatedResourceStatuses stores status of resource being resized for the given PVC. Key names "
            + "follow standard Kubernetes label syntax. Valid values are either:  * Un-prefixed keys:   - storage - "
            + "the capacity of the volume.  * Custom resources must use implementation-defined prefixed names such as"
            + " \"example.com/my-custom-resource\" Apart from above values - keys that are unprefixed or have "
            + "kubernetes.io prefix are considered reserved and hence may not be used.  ClaimResourceStatus can be in"
            + " any of following states:  - ControllerResizeInProgress:   State set when resize controller starts "
            + "resizing the volume in control-plane.  - ControllerResizeFailed:   State set when resize has failed in"
            + " resize controller with a terminal error.  - NodeResizePending:   State set when resize controller has"
            + " finished resizing the volume but further resizing of   volume is needed on the node.  - "
            + "NodeResizeInProgress:   State set when kubelet starts resizing the volume.  - NodeResizeFailed:   "
            + "State set when resizing has failed in kubelet with a terminal error. Transient errors don't set   "
            + "NodeResizeFailed. For example: if expanding a PVC for more capacity - this field can be one of the "
            + "following states:  - pvc.status.allocatedResourceStatus['storage'] = \"ControllerResizeInProgress\"   "
            + "   - pvc.status.allocatedResourceStatus['storage'] = \"ControllerResizeFailed\"      - pvc.status"
            + ".allocatedResourceStatus['storage'] = \"NodeResizePending\"      - pvc.status"
            + ".allocatedResourceStatus['storage'] = \"NodeResizeInProgress\"      - pvc.status"
            + ".allocatedResourceStatus['storage'] = \"NodeResizeFailed\" When this field is not set, it means that "
            + "no resize operation is in progress for the given PVC.  A controller that receives PVC update with "
            + "previously unknown resourceName or ClaimResourceStatus should ignore the update for the purpose it was"
            + " designed. For example - a controller that only is responsible for resizing capacity of the volume, "
            + "should ignore PVC updates that change other valid resources associated with PVC.  This is an alpha "
            + "field and requires enabling RecoverVolumeExpansionFailure feature.")

    public Map<String, String> getAllocatedResourceStatuses() {
        return allocatedResourceStatuses;
    }

    public void setAllocatedResourceStatuses(Map<String, String> allocatedResourceStatuses) {
        this.allocatedResourceStatuses = allocatedResourceStatuses;
    }

    public V1alpha1SandboxSetSpecStatus allocatedResources(Map<String, Quantity> allocatedResources) {

        this.allocatedResources = allocatedResources;
        return this;
    }

    public V1alpha1SandboxSetSpecStatus putAllocatedResourcesItem(String key, Quantity allocatedResourcesItem) {
        if (this.allocatedResources == null) {
            this.allocatedResources = new HashMap<>();
        }
        this.allocatedResources.put(key, allocatedResourcesItem);
        return this;
    }

    /**
     * allocatedResources tracks the resources allocated to a PVC including its capacity. Key names follow standard
     * Kubernetes label syntax. Valid values are either:  * Un-prefixed keys:   - storage - the capacity of the volume.
     * * Custom resources must use implementation-defined prefixed names such as
     * \&quot;example.com/my-custom-resource\&quot; Apart from above values - keys that are unprefixed or have
     * kubernetes.io prefix are considered reserved and hence may not be used.  Capacity reported here may be larger
     * than the actual capacity when a volume expansion operation is requested. For storage quota, the larger value from
     * allocatedResources and PVC.spec.resources is used. If allocatedResources is not set, PVC.spec.resources alone is
     * used for quota calculation. If a volume expansion capacity request is lowered, allocatedResources is only lowered
     * if there are no expansion operations in progress and if the actual volume capacity is equal or lower than the
     * requested capacity.  A controller that receives PVC update with previously unknown resourceName should ignore the
     * update for the purpose it was designed. For example - a controller that only is responsible for resizing capacity
     * of the volume, should ignore PVC updates that change other valid resources associated with PVC.  This is an alpha
     * field and requires enabling RecoverVolumeExpansionFailure feature.
     *
     * @return allocatedResources
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "allocatedResources tracks the resources allocated to a PVC including its capacity. Key names follow "
            + "standard Kubernetes label syntax. Valid values are either:  * Un-prefixed keys:   - storage - the "
            + "capacity of the volume.  * Custom resources must use implementation-defined prefixed names such as "
            + "\"example.com/my-custom-resource\" Apart from above values - keys that are unprefixed or have "
            + "kubernetes.io prefix are considered reserved and hence may not be used.  Capacity reported here may be"
            + " larger than the actual capacity when a volume expansion operation is requested. For storage quota, "
            + "the larger value from allocatedResources and PVC.spec.resources is used. If allocatedResources is not "
            + "set, PVC.spec.resources alone is used for quota calculation. If a volume expansion capacity request is"
            + " lowered, allocatedResources is only lowered if there are no expansion operations in progress and if "
            + "the actual volume capacity is equal or lower than the requested capacity.  A controller that receives "
            + "PVC update with previously unknown resourceName should ignore the update for the purpose it was "
            + "designed. For example - a controller that only is responsible for resizing capacity of the volume, "
            + "should ignore PVC updates that change other valid resources associated with PVC.  This is an alpha "
            + "field and requires enabling RecoverVolumeExpansionFailure feature.")

    public Map<String, Quantity> getAllocatedResources() {
        return allocatedResources;
    }

    public void setAllocatedResources(Map<String, Quantity> allocatedResources) {
        this.allocatedResources = allocatedResources;
    }

    public V1alpha1SandboxSetSpecStatus capacity(Map<String, Quantity> capacity) {

        this.capacity = capacity;
        return this;
    }

    public V1alpha1SandboxSetSpecStatus putCapacityItem(String key, Quantity capacityItem) {
        if (this.capacity == null) {
            this.capacity = new HashMap<>();
        }
        this.capacity.put(key, capacityItem);
        return this;
    }

    /**
     * capacity represents the actual resources of the underlying volume.
     *
     * @return capacity
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "capacity represents the actual resources of the underlying volume.")

    public Map<String, Quantity> getCapacity() {
        return capacity;
    }

    public void setCapacity(Map<String, Quantity> capacity) {
        this.capacity = capacity;
    }

    public V1alpha1SandboxSetSpecStatus conditions(List<V1alpha1SandboxSetSpecStatusConditions> conditions) {

        this.conditions = conditions;
        return this;
    }

    public V1alpha1SandboxSetSpecStatus addConditionsItem(V1alpha1SandboxSetSpecStatusConditions conditionsItem) {
        if (this.conditions == null) {
            this.conditions = new ArrayList<>();
        }
        this.conditions.add(conditionsItem);
        return this;
    }

    /**
     * conditions is the current Condition of persistent volume claim. If underlying persistent volume is being resized
     * then the Condition will be set to &#39;Resizing&#39;.
     *
     * @return conditions
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "conditions is the current Condition of persistent volume claim. If underlying persistent volume is "
            + "being resized then the Condition will be set to 'Resizing'.")

    public List<V1alpha1SandboxSetSpecStatusConditions> getConditions() {
        return conditions;
    }

    public void setConditions(List<V1alpha1SandboxSetSpecStatusConditions> conditions) {
        this.conditions = conditions;
    }

    public V1alpha1SandboxSetSpecStatus currentVolumeAttributesClassName(String currentVolumeAttributesClassName) {

        this.currentVolumeAttributesClassName = currentVolumeAttributesClassName;
        return this;
    }

    /**
     * currentVolumeAttributesClassName is the current name of the VolumeAttributesClass the PVC is using. When unset,
     * there is no VolumeAttributeClass applied to this PersistentVolumeClaim This is a beta field and requires enabling
     * VolumeAttributesClass feature (off by default).
     *
     * @return currentVolumeAttributesClassName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "currentVolumeAttributesClassName is the current name of the VolumeAttributesClass the PVC is using. "
            + "When unset, there is no VolumeAttributeClass applied to this PersistentVolumeClaim This is a beta "
            + "field and requires enabling VolumeAttributesClass feature (off by default).")

    public String getCurrentVolumeAttributesClassName() {
        return currentVolumeAttributesClassName;
    }

    public void setCurrentVolumeAttributesClassName(String currentVolumeAttributesClassName) {
        this.currentVolumeAttributesClassName = currentVolumeAttributesClassName;
    }

    public V1alpha1SandboxSetSpecStatus modifyVolumeStatus(
        V1alpha1SandboxSetSpecStatusModifyVolumeStatus modifyVolumeStatus) {

        this.modifyVolumeStatus = modifyVolumeStatus;
        return this;
    }

    /**
     * Get modifyVolumeStatus
     *
     * @return modifyVolumeStatus
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SandboxSetSpecStatusModifyVolumeStatus getModifyVolumeStatus() {
        return modifyVolumeStatus;
    }

    public void setModifyVolumeStatus(V1alpha1SandboxSetSpecStatusModifyVolumeStatus modifyVolumeStatus) {
        this.modifyVolumeStatus = modifyVolumeStatus;
    }

    public V1alpha1SandboxSetSpecStatus phase(String phase) {

        this.phase = phase;
        return this;
    }

    /**
     * phase represents the current phase of PersistentVolumeClaim.
     *
     * @return phase
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "phase represents the current phase of PersistentVolumeClaim.")

    public String getPhase() {
        return phase;
    }

    public void setPhase(String phase) {
        this.phase = phase;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SandboxSetSpecStatus v1alpha1SandboxSetSpecStatus = (V1alpha1SandboxSetSpecStatus)o;
        return Objects.equals(this.accessModes, v1alpha1SandboxSetSpecStatus.accessModes) &&
            Objects.equals(this.allocatedResourceStatuses, v1alpha1SandboxSetSpecStatus.allocatedResourceStatuses) &&
            Objects.equals(this.allocatedResources, v1alpha1SandboxSetSpecStatus.allocatedResources) &&
            Objects.equals(this.capacity, v1alpha1SandboxSetSpecStatus.capacity) &&
            Objects.equals(this.conditions, v1alpha1SandboxSetSpecStatus.conditions) &&
            Objects.equals(this.currentVolumeAttributesClassName,
                v1alpha1SandboxSetSpecStatus.currentVolumeAttributesClassName) &&
            Objects.equals(this.modifyVolumeStatus, v1alpha1SandboxSetSpecStatus.modifyVolumeStatus) &&
            Objects.equals(this.phase, v1alpha1SandboxSetSpecStatus.phase);
    }

    @Override
    public int hashCode() {
        return Objects.hash(accessModes, allocatedResourceStatuses, allocatedResources, capacity, conditions,
            currentVolumeAttributesClassName, modifyVolumeStatus, phase);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SandboxSetSpecStatus {\n");
        sb.append("    accessModes: ").append(toIndentedString(accessModes)).append("\n");
        sb.append("    allocatedResourceStatuses: ").append(toIndentedString(allocatedResourceStatuses)).append("\n");
        sb.append("    allocatedResources: ").append(toIndentedString(allocatedResources)).append("\n");
        sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
        sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
        sb.append("    currentVolumeAttributesClassName: ").append(toIndentedString(currentVolumeAttributesClassName))
            .append("\n");
        sb.append("    modifyVolumeStatus: ").append(toIndentedString(modifyVolumeStatus)).append("\n");
        sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

