/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.kubernetes.client.openapi.models.V1ObjectMeta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PersistentVolumeClaim is a user&#39;s request for and claim to a persistent volume
 */
@ApiModel(description = "PersistentVolumeClaim is a user's request for and claim to a persistent volume")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-01-23T10:04:45.718Z[Etc/UTC]")
public class V1alpha1SandboxSetSpecVolumeClaimTemplates {
    public static final String SERIALIZED_NAME_API_VERSION = "apiVersion";
    @SerializedName(SERIALIZED_NAME_API_VERSION)
    private String apiVersion;

    public static final String SERIALIZED_NAME_KIND = "kind";
    @SerializedName(SERIALIZED_NAME_KIND)
    private String kind;

    public static final String SERIALIZED_NAME_METADATA = "metadata";
    @SerializedName(SERIALIZED_NAME_METADATA)
    private V1ObjectMeta metadata;

    public static final String SERIALIZED_NAME_SPEC = "spec";
    @SerializedName(SERIALIZED_NAME_SPEC)
    private V1alpha1SandboxSetSpecSpec spec;

    public static final String SERIALIZED_NAME_STATUS = "status";
    @SerializedName(SERIALIZED_NAME_STATUS)
    private V1alpha1SandboxSetSpecStatus status;

    public V1alpha1SandboxSetSpecVolumeClaimTemplates apiVersion(String apiVersion) {

        this.apiVersion = apiVersion;
        return this;
    }

    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized
     * schemas to the latest internal value, and may reject unrecognized values. More info:
     * https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     *
     * @return apiVersion
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert "
            + "recognized schemas to the latest internal value, and may reject unrecognized values. More info: "
            + "https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources")

    public String getApiVersion() {
        return apiVersion;
    }

    public void setApiVersion(String apiVersion) {
        this.apiVersion = apiVersion;
    }

    public V1alpha1SandboxSetSpecVolumeClaimTemplates kind(String kind) {

        this.kind = kind;
        return this;
    }

    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the
     * endpoint the client submits requests to. Cannot be updated. In CamelCase. More info:
     * https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     *
     * @return kind
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "Kind is a string value representing the REST resource this object represents. Servers may infer this"
            + " from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: "
            + "https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds")

    public String getKind() {
        return kind;
    }

    public void setKind(String kind) {
        this.kind = kind;
    }

    public V1alpha1SandboxSetSpecVolumeClaimTemplates metadata(V1ObjectMeta metadata) {

        this.metadata = metadata;
        return this;
    }

    /**
     * Standard object&#39;s metadata. More info:
     * https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
     *
     * @return metadata
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "Standard object's metadata. More info: https://git.k8s"
            + ".io/community/contributors/devel/sig-architecture/api-conventions.md#metadata")

    public V1ObjectMeta getMetadata() {
        return metadata;
    }

    public void setMetadata(V1ObjectMeta metadata) {
        this.metadata = metadata;
    }

    public V1alpha1SandboxSetSpecVolumeClaimTemplates spec(V1alpha1SandboxSetSpecSpec spec) {

        this.spec = spec;
        return this;
    }

    /**
     * Get spec
     *
     * @return spec
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SandboxSetSpecSpec getSpec() {
        return spec;
    }

    public void setSpec(V1alpha1SandboxSetSpecSpec spec) {
        this.spec = spec;
    }

    public V1alpha1SandboxSetSpecVolumeClaimTemplates status(V1alpha1SandboxSetSpecStatus status) {

        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SandboxSetSpecStatus getStatus() {
        return status;
    }

    public void setStatus(V1alpha1SandboxSetSpecStatus status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SandboxSetSpecVolumeClaimTemplates v1alpha1SandboxSetSpecVolumeClaimTemplates
            = (V1alpha1SandboxSetSpecVolumeClaimTemplates)o;
        return Objects.equals(this.apiVersion, v1alpha1SandboxSetSpecVolumeClaimTemplates.apiVersion) &&
            Objects.equals(this.kind, v1alpha1SandboxSetSpecVolumeClaimTemplates.kind) &&
            Objects.equals(this.metadata, v1alpha1SandboxSetSpecVolumeClaimTemplates.metadata) &&
            Objects.equals(this.spec, v1alpha1SandboxSetSpecVolumeClaimTemplates.spec) &&
            Objects.equals(this.status, v1alpha1SandboxSetSpecVolumeClaimTemplates.status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(apiVersion, kind, metadata, spec, status);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SandboxSetSpecVolumeClaimTemplates {\n");
        sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
        sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
        sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
        sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

