/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;

/**
 * Pod Info
 */
@ApiModel(description = "Pod Info")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-01-23T10:04:45.718Z[Etc/UTC]")
public class V1alpha1SandboxStatusPodInfo {
    public static final String SERIALIZED_NAME_ANNOTATIONS = "annotations";
    @SerializedName(SERIALIZED_NAME_ANNOTATIONS)
    private Map<String, String> annotations = null;

    public static final String SERIALIZED_NAME_LABELS = "labels";
    @SerializedName(SERIALIZED_NAME_LABELS)
    private Map<String, String> labels = null;

    public static final String SERIALIZED_NAME_NODE_NAME = "nodeName";
    @SerializedName(SERIALIZED_NAME_NODE_NAME)
    private String nodeName;

    public static final String SERIALIZED_NAME_POD_I_P = "podIP";
    @SerializedName(SERIALIZED_NAME_POD_I_P)
    private String podIP;

    public static final String SERIALIZED_NAME_POD_U_I_D = "podUID";
    @SerializedName(SERIALIZED_NAME_POD_U_I_D)
    private String podUID;

    public V1alpha1SandboxStatusPodInfo annotations(Map<String, String> annotations) {

        this.annotations = annotations;
        return this;
    }

    public V1alpha1SandboxStatusPodInfo putAnnotationsItem(String key, String annotationsItem) {
        if (this.annotations == null) {
            this.annotations = new HashMap<>();
        }
        this.annotations.put(key, annotationsItem);
        return this;
    }

    /**
     * Annotations contains pod important annotations
     *
     * @return annotations
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Annotations contains pod important annotations")

    public Map<String, String> getAnnotations() {
        return annotations;
    }

    public void setAnnotations(Map<String, String> annotations) {
        this.annotations = annotations;
    }

    public V1alpha1SandboxStatusPodInfo labels(Map<String, String> labels) {

        this.labels = labels;
        return this;
    }

    public V1alpha1SandboxStatusPodInfo putLabelsItem(String key, String labelsItem) {
        if (this.labels == null) {
            this.labels = new HashMap<>();
        }
        this.labels.put(key, labelsItem);
        return this;
    }

    /**
     * Labels contains pod important labels
     *
     * @return labels
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Labels contains pod important labels")

    public Map<String, String> getLabels() {
        return labels;
    }

    public void setLabels(Map<String, String> labels) {
        this.labels = labels;
    }

    public V1alpha1SandboxStatusPodInfo nodeName(String nodeName) {

        this.nodeName = nodeName;
        return this;
    }

    /**
     * NodeName indicates in which node this pod is scheduled.
     *
     * @return nodeName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "NodeName indicates in which node this pod is scheduled.")

    public String getNodeName() {
        return nodeName;
    }

    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    public V1alpha1SandboxStatusPodInfo podIP(String podIP) {

        this.podIP = podIP;
        return this;
    }

    /**
     * PodIP address allocated to the pod.
     *
     * @return podIP
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "PodIP address allocated to the pod.")

    public String getPodIP() {
        return podIP;
    }

    public void setPodIP(String podIP) {
        this.podIP = podIP;
    }

    public V1alpha1SandboxStatusPodInfo podUID(String podUID) {

        this.podUID = podUID;
        return this;
    }

    /**
     * PodUID is pod uid.
     *
     * @return podUID
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "PodUID is pod uid.")

    public String getPodUID() {
        return podUID;
    }

    public void setPodUID(String podUID) {
        this.podUID = podUID;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SandboxStatusPodInfo v1alpha1SandboxStatusPodInfo = (V1alpha1SandboxStatusPodInfo)o;
        return Objects.equals(this.annotations, v1alpha1SandboxStatusPodInfo.annotations) &&
            Objects.equals(this.labels, v1alpha1SandboxStatusPodInfo.labels) &&
            Objects.equals(this.nodeName, v1alpha1SandboxStatusPodInfo.nodeName) &&
            Objects.equals(this.podIP, v1alpha1SandboxStatusPodInfo.podIP) &&
            Objects.equals(this.podUID, v1alpha1SandboxStatusPodInfo.podUID);
    }

    @Override
    public int hashCode() {
        return Objects.hash(annotations, labels, nodeName, podIP, podUID);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SandboxStatusPodInfo {\n");
        sb.append("    annotations: ").append(toIndentedString(annotations)).append("\n");
        sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
        sb.append("    nodeName: ").append(toIndentedString(nodeName)).append("\n");
        sb.append("    podIP: ").append(toIndentedString(podIP)).append("\n");
        sb.append("    podUID: ").append(toIndentedString(podUID)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

