/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * status defines the observed state of SandboxSet
 */
@ApiModel(description = "status defines the observed state of SandboxSet")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-01-23T10:04:45.718Z[Etc/UTC]")
public class V1alpha1SandboxSetStatus {
    public static final String SERIALIZED_NAME_AVAILABLE_REPLICAS = "availableReplicas";
    @SerializedName(SERIALIZED_NAME_AVAILABLE_REPLICAS)
    private Integer availableReplicas;

    public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
    @SerializedName(SERIALIZED_NAME_CONDITIONS)
    private List<V1alpha1SandboxSetStatusConditions> conditions = null;

    public static final String SERIALIZED_NAME_OBSERVED_GENERATION = "observedGeneration";
    @SerializedName(SERIALIZED_NAME_OBSERVED_GENERATION)
    private Long observedGeneration;

    public static final String SERIALIZED_NAME_REPLICAS = "replicas";
    @SerializedName(SERIALIZED_NAME_REPLICAS)
    private Integer replicas;

    public static final String SERIALIZED_NAME_SELECTOR = "selector";
    @SerializedName(SERIALIZED_NAME_SELECTOR)
    private String selector;

    public static final String SERIALIZED_NAME_UPDATE_REVISION = "updateRevision";
    @SerializedName(SERIALIZED_NAME_UPDATE_REVISION)
    private String updateRevision;

    public V1alpha1SandboxSetStatus availableReplicas(Integer availableReplicas) {

        this.availableReplicas = availableReplicas;
        return this;
    }

    /**
     * AvailableReplicas is the number of available sandboxes, which are ready to be claimed.
     *
     * @return availableReplicas
     **/
    @ApiModelProperty(required = true,
        value = "AvailableReplicas is the number of available sandboxes, which are ready to be claimed.")

    public Integer getAvailableReplicas() {
        return availableReplicas;
    }

    public void setAvailableReplicas(Integer availableReplicas) {
        this.availableReplicas = availableReplicas;
    }

    public V1alpha1SandboxSetStatus conditions(List<V1alpha1SandboxSetStatusConditions> conditions) {

        this.conditions = conditions;
        return this;
    }

    public V1alpha1SandboxSetStatus addConditionsItem(V1alpha1SandboxSetStatusConditions conditionsItem) {
        if (this.conditions == null) {
            this.conditions = new ArrayList<>();
        }
        this.conditions.add(conditionsItem);
        return this;
    }

    /**
     * conditions represent the current state of the SandboxSet resource. Each condition has a unique type and reflects
     * the status of a specific aspect of the resource. The status of each condition is one of True, False, or Unknown.
     *
     * @return conditions
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "conditions represent the current state of the SandboxSet resource. Each condition has a unique type "
            + "and reflects the status of a specific aspect of the resource. The status of each condition is one of "
            + "True, False, or Unknown.")

    public List<V1alpha1SandboxSetStatusConditions> getConditions() {
        return conditions;
    }

    public void setConditions(List<V1alpha1SandboxSetStatusConditions> conditions) {
        this.conditions = conditions;
    }

    public V1alpha1SandboxSetStatus observedGeneration(Long observedGeneration) {

        this.observedGeneration = observedGeneration;
        return this;
    }

    /**
     * observedGeneration is the most recent generation observed for this SandboxSet. It corresponds to the
     * SandboxSet&#39;s generation, which is updated on mutation by the API Server.
     *
     * @return observedGeneration
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "observedGeneration is the most recent generation observed for this SandboxSet. It corresponds to the"
            + " SandboxSet's generation, which is updated on mutation by the API Server.")

    public Long getObservedGeneration() {
        return observedGeneration;
    }

    public void setObservedGeneration(Long observedGeneration) {
        this.observedGeneration = observedGeneration;
    }

    public V1alpha1SandboxSetStatus replicas(Integer replicas) {

        this.replicas = replicas;
        return this;
    }

    /**
     * Replicas is the total number of creating, available, running and paused sandboxes.
     *
     * @return replicas
     **/
    @ApiModelProperty(required = true,
        value = "Replicas is the total number of creating, available, running and paused sandboxes.")

    public Integer getReplicas() {
        return replicas;
    }

    public void setReplicas(Integer replicas) {
        this.replicas = replicas;
    }

    public V1alpha1SandboxSetStatus selector(String selector) {

        this.selector = selector;
        return this;
    }

    /**
     * Selector is a label query over pods that should match the replica count. This is same as the label selector but
     * in the string format to avoid duplication for CRDs that do not support structural schemas.
     *
     * @return selector
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "Selector is a label query over pods that should match the replica count. This is same as the label "
            + "selector but in the string format to avoid duplication for CRDs that do not support structural schemas.")

    public String getSelector() {
        return selector;
    }

    public void setSelector(String selector) {
        this.selector = selector;
    }

    public V1alpha1SandboxSetStatus updateRevision(String updateRevision) {

        this.updateRevision = updateRevision;
        return this;
    }

    /**
     * UpdateRevision is the template-hash calculated from &#x60;spec.template&#x60;.
     *
     * @return updateRevision
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "UpdateRevision is the template-hash calculated from `spec.template`.")

    public String getUpdateRevision() {
        return updateRevision;
    }

    public void setUpdateRevision(String updateRevision) {
        this.updateRevision = updateRevision;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SandboxSetStatus v1alpha1SandboxSetStatus = (V1alpha1SandboxSetStatus)o;
        return Objects.equals(this.availableReplicas, v1alpha1SandboxSetStatus.availableReplicas) &&
            Objects.equals(this.conditions, v1alpha1SandboxSetStatus.conditions) &&
            Objects.equals(this.observedGeneration, v1alpha1SandboxSetStatus.observedGeneration) &&
            Objects.equals(this.replicas, v1alpha1SandboxSetStatus.replicas) &&
            Objects.equals(this.selector, v1alpha1SandboxSetStatus.selector) &&
            Objects.equals(this.updateRevision, v1alpha1SandboxSetStatus.updateRevision);
    }

    @Override
    public int hashCode() {
        return Objects.hash(availableReplicas, conditions, observedGeneration, replicas, selector, updateRevision);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SandboxSetStatus {\n");
        sb.append("    availableReplicas: ").append(toIndentedString(availableReplicas)).append("\n");
        sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
        sb.append("    observedGeneration: ").append(toIndentedString(observedGeneration)).append("\n");
        sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
        sb.append("    selector: ").append(toIndentedString(selector)).append("\n");
        sb.append("    updateRevision: ").append(toIndentedString(updateRevision)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

