/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ModifyVolumeStatus represents the status object of ControllerModifyVolume operation. When this is unset, there is no
 * ModifyVolume operation being attempted. This is a beta field and requires enabling VolumeAttributesClass feature (off
 * by default).
 */
@ApiModel(
    description = "ModifyVolumeStatus represents the status object of ControllerModifyVolume operation. When this is "
        + "unset, there is no ModifyVolume operation being attempted. This is a beta field and requires enabling "
        + "VolumeAttributesClass feature (off by default).")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-01-23T10:04:45.718Z[Etc/UTC]")
public class V1alpha1SandboxSetSpecStatusModifyVolumeStatus {
    public static final String SERIALIZED_NAME_STATUS = "status";
    @SerializedName(SERIALIZED_NAME_STATUS)
    private String status;

    public static final String SERIALIZED_NAME_TARGET_VOLUME_ATTRIBUTES_CLASS_NAME = "targetVolumeAttributesClassName";
    @SerializedName(SERIALIZED_NAME_TARGET_VOLUME_ATTRIBUTES_CLASS_NAME)
    private String targetVolumeAttributesClassName;

    public V1alpha1SandboxSetSpecStatusModifyVolumeStatus status(String status) {

        this.status = status;
        return this;
    }

    /**
     * status is the status of the ControllerModifyVolume operation. It can be in any of following states:  - Pending
     * Pending indicates that the PersistentVolumeClaim cannot be modified due to unmet requirements, such as    the
     * specified VolumeAttributesClass not existing.  - InProgress    InProgress indicates that the volume is being
     * modified.  - Infeasible   Infeasible indicates that the request has been rejected as invalid by the CSI driver.
     * To    resolve the error, a valid VolumeAttributesClass needs to be specified. Note: New statuses can be added in
     * the future. Consumers should check for unknown statuses and fail appropriately.
     *
     * @return status
     **/
    @ApiModelProperty(required = true,
        value = "status is the status of the ControllerModifyVolume operation. It can be in any of following states: "
            + " - Pending    Pending indicates that the PersistentVolumeClaim cannot be modified due to unmet "
            + "requirements, such as    the specified VolumeAttributesClass not existing.  - InProgress    InProgress"
            + " indicates that the volume is being modified.  - Infeasible   Infeasible indicates that the request "
            + "has been rejected as invalid by the CSI driver. To    resolve the error, a valid VolumeAttributesClass"
            + " needs to be specified. Note: New statuses can be added in the future. Consumers should check for "
            + "unknown statuses and fail appropriately.")

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public V1alpha1SandboxSetSpecStatusModifyVolumeStatus targetVolumeAttributesClassName(
        String targetVolumeAttributesClassName) {

        this.targetVolumeAttributesClassName = targetVolumeAttributesClassName;
        return this;
    }

    /**
     * targetVolumeAttributesClassName is the name of the VolumeAttributesClass the PVC currently being reconciled
     *
     * @return targetVolumeAttributesClassName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "targetVolumeAttributesClassName is the name of the VolumeAttributesClass the PVC currently being "
            + "reconciled")

    public String getTargetVolumeAttributesClassName() {
        return targetVolumeAttributesClassName;
    }

    public void setTargetVolumeAttributesClassName(String targetVolumeAttributesClassName) {
        this.targetVolumeAttributesClassName = targetVolumeAttributesClassName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SandboxSetSpecStatusModifyVolumeStatus v1alpha1SandboxSetSpecStatusModifyVolumeStatus
            = (V1alpha1SandboxSetSpecStatusModifyVolumeStatus)o;
        return Objects.equals(this.status, v1alpha1SandboxSetSpecStatusModifyVolumeStatus.status) &&
            Objects.equals(this.targetVolumeAttributesClassName,
                v1alpha1SandboxSetSpecStatusModifyVolumeStatus.targetVolumeAttributesClassName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(status, targetVolumeAttributesClassName);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SandboxSetSpecStatusModifyVolumeStatus {\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    targetVolumeAttributesClassName: ").append(toIndentedString(targetVolumeAttributesClassName))
            .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

