/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.kubernetes.client.custom.Quantity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;

/**
 * resources represents the minimum resources the volume should have. If RecoverVolumeExpansionFailure feature is
 * enabled users are allowed to specify resource requirements that are lower than previous value but must still be
 * higher than capacity recorded in the status field of the claim. More info:
 * https://kubernetes.io/docs/concepts/storage/persistent-volumes#resources
 */
@ApiModel(
    description = "resources represents the minimum resources the volume should have. If "
        + "RecoverVolumeExpansionFailure feature is enabled users are allowed to specify resource requirements that "
        + "are lower than previous value but must still be higher than capacity recorded in the status field of the "
        + "claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#resources")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-01-23T10:04:45.718Z[Etc/UTC]")
public class V1alpha1SandboxSetSpecSpecResources {
    public static final String SERIALIZED_NAME_LIMITS = "limits";
    @SerializedName(SERIALIZED_NAME_LIMITS)
    private Map<String, Quantity> limits = null;

    public static final String SERIALIZED_NAME_REQUESTS = "requests";
    @SerializedName(SERIALIZED_NAME_REQUESTS)
    private Map<String, Quantity> requests = null;

    public V1alpha1SandboxSetSpecSpecResources limits(Map<String, Quantity> limits) {
        this.limits = limits;
        return this;
    }

    public V1alpha1SandboxSetSpecSpecResources putLimitsItem(String key, Quantity limitsItem) {
        if (this.limits == null) {
            this.limits = new HashMap<>();
        }
        this.limits.put(key, limitsItem);
        return this;
    }

    /**
     * Limits describes the maximum amount of compute resources allowed. More info:
     * https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
     *
     * @return limits
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes"
            + ".io/docs/concepts/configuration/manage-resources-containers/")

    public Map<String, Quantity> getLimits() {
        return limits;
    }

    public void setLimits(Map<String, Quantity> limits) {
        this.limits = limits;
    }

    public V1alpha1SandboxSetSpecSpecResources requests(Map<String, Quantity> requests) {

        this.requests = requests;
        return this;
    }

    public V1alpha1SandboxSetSpecSpecResources putRequestsItem(String key, Quantity requestsItem) {
        if (this.requests == null) {
            this.requests = new HashMap<>();
        }
        this.requests.put(key, requestsItem);
        return this;
    }

    /**
     * Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it
     * defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. Requests cannot
     * exceed Limits. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
     *
     * @return requests
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "Requests describes the minimum amount of compute resources required. If Requests is omitted for a "
            + "container, it defaults to Limits if that is explicitly specified, otherwise to an "
            + "implementation-defined value. Requests cannot exceed Limits. More info: https://kubernetes"
            + ".io/docs/concepts/configuration/manage-resources-containers/")

    public Map<String, Quantity> getRequests() {
        return requests;
    }

    public void setRequests(Map<String, Quantity> requests) {
        this.requests = requests;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SandboxSetSpecSpecResources v1alpha1SandboxSetSpecSpecResources
            = (V1alpha1SandboxSetSpecSpecResources)o;
        return Objects.equals(this.limits, v1alpha1SandboxSetSpecSpecResources.limits) &&
            Objects.equals(this.requests, v1alpha1SandboxSetSpecSpecResources.requests);
    }

    @Override
    public int hashCode() {
        return Objects.hash(limits, requests);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SandboxSetSpecSpecResources {\n");
        sb.append("    limits: ").append(toIndentedString(limits)).append("\n");
        sb.append("    requests: ").append(toIndentedString(requests)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

