/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * dataSource field can be used to specify either: * An existing VolumeSnapshot object
 * (snapshot.storage.k8s.io/VolumeSnapshot) * An existing PVC (PersistentVolumeClaim) If the provisioner or an external
 * controller can support the specified data source, it will create a new volume based on the contents of the specified
 * data source. When the AnyVolumeDataSource feature gate is enabled, dataSource contents will be copied to
 * dataSourceRef, and dataSourceRef contents will be copied to dataSource when dataSourceRef.namespace is not specified.
 * If the namespace is specified, then dataSourceRef will not be copied to dataSource.
 */
@ApiModel(
    description = "dataSource field can be used to specify either: * An existing VolumeSnapshot object (snapshot"
        + ".storage.k8s.io/VolumeSnapshot) * An existing PVC (PersistentVolumeClaim) If the provisioner or an "
        + "external controller can support the specified data source, it will create a new volume based on the "
        + "contents of the specified data source. When the AnyVolumeDataSource feature gate is enabled, dataSource "
        + "contents will be copied to dataSourceRef, and dataSourceRef contents will be copied to dataSource when "
        + "dataSourceRef.namespace is not specified. If the namespace is specified, then dataSourceRef will not be "
        + "copied to dataSource.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-01-23T10:04:45.718Z[Etc/UTC]")
public class V1alpha1SandboxSetSpecSpecDataSource {
    public static final String SERIALIZED_NAME_API_GROUP = "apiGroup";
    @SerializedName(SERIALIZED_NAME_API_GROUP)
    private String apiGroup;

    public static final String SERIALIZED_NAME_KIND = "kind";
    @SerializedName(SERIALIZED_NAME_KIND)
    private String kind;

    public static final String SERIALIZED_NAME_NAME = "name";
    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;

    public V1alpha1SandboxSetSpecSpecDataSource apiGroup(String apiGroup) {

        this.apiGroup = apiGroup;
        return this;
    }

    /**
     * APIGroup is the group for the resource being referenced. If APIGroup is not specified, the specified Kind must be
     * in the core API group. For any other third-party types, APIGroup is required.
     *
     * @return apiGroup
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "APIGroup is the group for the resource being referenced. If APIGroup is not specified, the specified"
            + " Kind must be in the core API group. For any other third-party types, APIGroup is required.")

    public String getApiGroup() {
        return apiGroup;
    }

    public void setApiGroup(String apiGroup) {
        this.apiGroup = apiGroup;
    }

    public V1alpha1SandboxSetSpecSpecDataSource kind(String kind) {

        this.kind = kind;
        return this;
    }

    /**
     * Kind is the type of resource being referenced
     *
     * @return kind
     **/
    @ApiModelProperty(required = true, value = "Kind is the type of resource being referenced")

    public String getKind() {
        return kind;
    }

    public void setKind(String kind) {
        this.kind = kind;
    }

    public V1alpha1SandboxSetSpecSpecDataSource name(String name) {

        this.name = name;
        return this;
    }

    /**
     * Name is the name of resource being referenced
     *
     * @return name
     **/
    @ApiModelProperty(required = true, value = "Name is the name of resource being referenced")

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SandboxSetSpecSpecDataSource v1alpha1SandboxSetSpecSpecDataSource
            = (V1alpha1SandboxSetSpecSpecDataSource)o;
        return Objects.equals(this.apiGroup, v1alpha1SandboxSetSpecSpecDataSource.apiGroup) &&
            Objects.equals(this.kind, v1alpha1SandboxSetSpecSpecDataSource.kind) &&
            Objects.equals(this.name, v1alpha1SandboxSetSpecSpecDataSource.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(apiGroup, kind, name);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SandboxSetSpecSpecDataSource {\n");
        sb.append("    apiGroup: ").append(toIndentedString(apiGroup)).append("\n");
        sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

