/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * status defines the observed state of Sandbox
 */
@ApiModel(description = "status defines the observed state of Sandbox")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-01-23T10:04:45.718Z[Etc/UTC]")
public class V1alpha1SandboxStatus {
    public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
    @SerializedName(SERIALIZED_NAME_CONDITIONS)
    private List<V1alpha1SandboxSetStatusConditions> conditions = null;

    public static final String SERIALIZED_NAME_MESSAGE = "message";
    @SerializedName(SERIALIZED_NAME_MESSAGE)
    private String message;

    public static final String SERIALIZED_NAME_NODE_NAME = "nodeName";
    @SerializedName(SERIALIZED_NAME_NODE_NAME)
    private String nodeName;

    public static final String SERIALIZED_NAME_OBSERVED_GENERATION = "observedGeneration";
    @SerializedName(SERIALIZED_NAME_OBSERVED_GENERATION)
    private Long observedGeneration;

    public static final String SERIALIZED_NAME_PHASE = "phase";
    @SerializedName(SERIALIZED_NAME_PHASE)
    private String phase;

    public static final String SERIALIZED_NAME_POD_INFO = "podInfo";
    @SerializedName(SERIALIZED_NAME_POD_INFO)
    private V1alpha1SandboxStatusPodInfo podInfo;

    public static final String SERIALIZED_NAME_SANDBOX_IP = "sandboxIp";
    @SerializedName(SERIALIZED_NAME_SANDBOX_IP)
    private String sandboxIp;

    public static final String SERIALIZED_NAME_UPDATE_REVISION = "updateRevision";
    @SerializedName(SERIALIZED_NAME_UPDATE_REVISION)
    private String updateRevision;

    public V1alpha1SandboxStatus conditions(List<V1alpha1SandboxSetStatusConditions> conditions) {

        this.conditions = conditions;
        return this;
    }

    public V1alpha1SandboxStatus addConditionsItem(V1alpha1SandboxSetStatusConditions conditionsItem) {
        if (this.conditions == null) {
            this.conditions = new ArrayList<>();
        }
        this.conditions.add(conditionsItem);
        return this;
    }

    /**
     * conditions represent the current state of the Sandbox resource. Each condition has a unique type and reflects the
     * status of a specific aspect of the resource. The status of each condition is one of True, False, or Unknown.
     *
     * @return conditions
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "conditions represent the current state of the Sandbox resource. Each condition has a unique type and"
            + " reflects the status of a specific aspect of the resource. The status of each condition is one of "
            + "True, False, or Unknown.")

    public List<V1alpha1SandboxSetStatusConditions> getConditions() {
        return conditions;
    }

    public void setConditions(List<V1alpha1SandboxSetStatusConditions> conditions) {
        this.conditions = conditions;
    }

    public V1alpha1SandboxStatus message(String message) {

        this.message = message;
        return this;
    }

    /**
     * message
     *
     * @return message
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "message")

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public V1alpha1SandboxStatus nodeName(String nodeName) {

        this.nodeName = nodeName;
        return this;
    }

    /**
     * NodeName indicates in which node this sandbox is scheduled.
     *
     * @return nodeName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "NodeName indicates in which node this sandbox is scheduled.")

    public String getNodeName() {
        return nodeName;
    }

    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    public V1alpha1SandboxStatus observedGeneration(Long observedGeneration) {

        this.observedGeneration = observedGeneration;
        return this;
    }

    /**
     * observedGeneration is the most recent generation observed for this Sandbox. It corresponds to the Sandbox&#39;s
     * generation, which is updated on mutation by the API Server.
     *
     * @return observedGeneration
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "observedGeneration is the most recent generation observed for this Sandbox. It corresponds to the "
            + "Sandbox's generation, which is updated on mutation by the API Server.")

    public Long getObservedGeneration() {
        return observedGeneration;
    }

    public void setObservedGeneration(Long observedGeneration) {
        this.observedGeneration = observedGeneration;
    }

    public V1alpha1SandboxStatus phase(String phase) {

        this.phase = phase;
        return this;
    }

    /**
     * Sandbox Phase
     *
     * @return phase
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Sandbox Phase")

    public String getPhase() {
        return phase;
    }

    public void setPhase(String phase) {
        this.phase = phase;
    }

    public V1alpha1SandboxStatus podInfo(V1alpha1SandboxStatusPodInfo podInfo) {

        this.podInfo = podInfo;
        return this;
    }

    /**
     * Get podInfo
     *
     * @return podInfo
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SandboxStatusPodInfo getPodInfo() {
        return podInfo;
    }

    public void setPodInfo(V1alpha1SandboxStatusPodInfo podInfo) {
        this.podInfo = podInfo;
    }

    public V1alpha1SandboxStatus sandboxIp(String sandboxIp) {

        this.sandboxIp = sandboxIp;
        return this;
    }

    /**
     * SandboxIp is the ip address allocated to the sandbox.
     *
     * @return sandboxIp
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "SandboxIp is the ip address allocated to the sandbox.")

    public String getSandboxIp() {
        return sandboxIp;
    }

    public void setSandboxIp(String sandboxIp) {
        this.sandboxIp = sandboxIp;
    }

    public V1alpha1SandboxStatus updateRevision(String updateRevision) {

        this.updateRevision = updateRevision;
        return this;
    }

    /**
     * UpdateRevision is the template-hash calculated from &#x60;spec.template&#x60;.
     *
     * @return updateRevision
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "UpdateRevision is the template-hash calculated from `spec.template`.")

    public String getUpdateRevision() {
        return updateRevision;
    }

    public void setUpdateRevision(String updateRevision) {
        this.updateRevision = updateRevision;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SandboxStatus v1alpha1SandboxStatus = (V1alpha1SandboxStatus)o;
        return Objects.equals(this.conditions, v1alpha1SandboxStatus.conditions) &&
            Objects.equals(this.message, v1alpha1SandboxStatus.message) &&
            Objects.equals(this.nodeName, v1alpha1SandboxStatus.nodeName) &&
            Objects.equals(this.observedGeneration, v1alpha1SandboxStatus.observedGeneration) &&
            Objects.equals(this.phase, v1alpha1SandboxStatus.phase) &&
            Objects.equals(this.podInfo, v1alpha1SandboxStatus.podInfo) &&
            Objects.equals(this.sandboxIp, v1alpha1SandboxStatus.sandboxIp) &&
            Objects.equals(this.updateRevision, v1alpha1SandboxStatus.updateRevision);
    }

    @Override
    public int hashCode() {
        return Objects.hash(conditions, message, nodeName, observedGeneration, phase, podInfo, sandboxIp,
            updateRevision);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SandboxStatus {\n");
        sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    nodeName: ").append(toIndentedString(nodeName)).append("\n");
        sb.append("    observedGeneration: ").append(toIndentedString(observedGeneration)).append("\n");
        sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
        sb.append("    podInfo: ").append(toIndentedString(podInfo)).append("\n");
        sb.append("    sandboxIp: ").append(toIndentedString(sandboxIp)).append("\n");
        sb.append("    updateRevision: ").append(toIndentedString(updateRevision)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

